OPTIONS = -g -Wall -w
INCLUDE = -I/usr/local/include/ 
LIBPATH = -L/usr/local/lib/ 

# FREE_LIBS = -L/usr/local/lib -lfreenect
# GL_LIBS = -lglui -lglut -lGLU -lGL 
# GL_FLAGS = -L/usr/X11R6/lib -L/usr/lib -L/lib
# CFLAGS=-fPIC -g -Wall `pkg-config --cflags opencv` $(INCLUDE)

#%:%.cpp
#	g++ $(INCPATH) $(LIBPATH) $(OPTIONS) $^ -o $@

all:
	g++ main.cpp -o main matriz.cpp vector.cpp $(OPTIONS) 
